import type { Baby, MediaItem, Memory, MemoryType, Milestone } from '../lib/types';

/**
 * The demo family: Juno Hale, born September 14, 2025, and the first year of
 * little things Maya and Sam wrote down. Captions speak to Juno in the second
 * person, the way most parents actually write in a baby book.
 *
 * Media keys point at files in public/demo (generated by
 * scripts/generate-demo-media.py). Photos ending in a multiple of 4 are
 * landscape; video durations match the generated clips.
 */

export const DEMO_BABY_ID = 'baby-juno';
const CREATED = '2026-10-01T09:00:00.000Z';

const VIDEO_SECONDS: Record<string, number> = {
  'clip-01': 9, 'clip-02': 14, 'clip-03': 7, 'clip-04': 12, 'clip-05': 17, 'clip-06': 10, 'clip-07': 8,
  'clip-08': 11, 'clip-09': 13, 'clip-10': 6, 'clip-11': 15, 'clip-12': 9, 'clip-13': 12,
};

function mediaFor(key: string): MediaItem {
  if (key.startsWith('clip-')) {
    return {
      id: `m-${key}`, kind: 'video', storageProvider: 'demo', storageKey: `${key}.mp4`,
      thumbnailUrl: undefined, mimeType: 'video/mp4', width: 540, height: 676,
      duration: VIDEO_SECONDS[key], createdAt: CREATED, metadata: { poster: `${key}.jpg` },
    };
  }
  const n = parseInt(key.split('-')[1], 10);
  const landscape = n % 4 === 0;
  return {
    id: `m-${key}`, kind: 'photo', storageProvider: 'demo', storageKey: `${key}.jpg`,
    mimeType: 'image/jpeg', width: landscape ? 1200 : 960, height: landscape ? 900 : 1200,
    createdAt: CREATED, metadata: { thumb: `${key}.thumb.jpg` },
  };
}

interface SeedRow {
  d: string; t: MemoryType; title?: string; c?: string; m?: string[];
  loc?: string; who?: string[]; tags?: string[]; fav?: boolean; ms?: string;
}

const rows: SeedRow[] = [
  // ── September 2025 ──────────────────────────────────────────
  { d: '2025-09-14', t: 'milestone', title: 'Hello, Juno', ms: 'Born',
    c: "4:12 in the morning, 7 lb 2 oz. You arrived in a hurry and then looked around the room like you'd been expecting us.",
    m: ['morning-01', 'linen-02'], loc: "St. Vincent's", who: ['Mom', 'Dad'], fav: true, tags: ['birth'] },
  { d: '2025-09-15', t: 'first', title: 'Meeting Grandma & Grandpa', ms: 'Met grandparents',
    c: 'Grandma Ruth and Grandpa Lou drove through the night. Grandpa held you for an hour and refused to give you back.',
    m: ['window-01', 'window-02'], loc: "St. Vincent's", who: ['Grandma Ruth', 'Grandpa Lou'], tags: ['family'] },
  { d: '2025-09-16', t: 'first', title: 'The first night home', ms: 'First night home',
    c: 'Finally home. You slept through most of the night, which felt like a miracle.',
    m: ['night-01'], loc: 'Home', who: ['Mom', 'Dad'], fav: true },
  { d: '2025-09-17', t: 'funny', title: 'Tiny yawns', c: 'The yawn that took up your whole face.', m: ['clip-01'], loc: 'Home' },
  { d: '2025-09-19', t: 'story', title: 'The drive home',
    c: "Dad drove eleven miles an hour below the speed limit the whole way. Every pothole felt like a personal attack. Mom sat in the back with her hand on your chest and neither of us said a word until we pulled into the driveway, and then we both started laughing, because we had no idea what to do next.",
    m: ['window-03'], who: ['Mom', 'Dad'] },
  { d: '2025-09-21', t: 'family', title: 'Biscuit meets you',
    c: "Biscuit sniffed your feet very seriously and then lay down beside the bassinet. He hasn't really left since.",
    m: ['linen-01', 'window-04'], loc: 'Home', tags: ['biscuit', 'dog'] },
  { d: '2025-09-23', t: 'first', title: 'First bath', ms: 'First bath',
    c: 'You were furious for about forty seconds, then decided it was the best thing that had ever happened.',
    m: ['morning-02', 'morning-03'], loc: 'Home', who: ['Dad'] },
  { d: '2025-09-26', t: 'funny', title: 'Milk drunk', c: 'Eyebrows up, mouth open, completely gone.', m: ['linen-03'] },
  { d: '2025-09-28', t: 'moment', title: "Dad's chest, your favorite bed", m: ['window-05'], who: ['Dad'] },
  { d: '2025-09-30', t: 'story', title: 'Three in the morning',
    c: "It's three in the morning and the house is so quiet I can hear the fridge. You're asleep on me and I'm afraid to breathe too loudly. I keep thinking I should put you down and sleep, and I keep not doing it. I want to remember exactly how heavy you are right now. — Mom",
    who: ['Mom'] },

  // ── October 2025 ────────────────────────────────────────────
  { d: '2025-10-02', t: 'moment', title: 'First walk around the block',
    c: 'Bundled up like a burrito. You slept through the whole thing, so it was mostly for us.',
    m: ['autumn-01', 'autumn-02', 'autumn-03'], loc: 'Our street', who: ['Mom', 'Dad'] },
  { d: '2025-10-08', t: 'funny', title: 'The hiccups',
    c: 'Twenty minutes of hiccups. You seemed personally offended by every single one.', m: ['clip-02'] },
  { d: '2025-10-11', t: 'family', title: "Nana Rosa's quilt",
    c: 'Nana Rosa finished the quilt she started the day we told her about you. Every square is a fabric from someone in the family.',
    m: ['linen-04'], who: ['Nana Rosa'], tags: ['gift'] },
  { d: '2025-10-15', t: 'moment', m: ['window-06'] },
  { d: '2025-10-18', t: 'moment', title: 'Sunday morning', m: ['morning-06', 'linen-05'], loc: 'Home' },
  { d: '2025-10-22', t: 'moment', title: 'Asleep at the farmers market',
    c: 'Somewhere between the peaches and the flowers.', m: ['autumn-04'], loc: 'Farmers market' },
  { d: '2025-10-28', t: 'milestone', title: 'First smile', ms: 'First smile',
    c: "We'd been trying all morning. Then suddenly you looked right at Mom and smiled.",
    m: ['morning-04', 'morning-05'], who: ['Mom'], fav: true },
  { d: '2025-10-31', t: 'first', title: 'First Halloween', ms: 'First Halloween',
    c: 'A very small pumpkin. Biscuit was a slightly bigger pumpkin. Neither of you consented.',
    m: ['autumn-05', 'autumn-06'], tags: ['holiday', 'halloween', 'biscuit'] },

  // ── November 2025 ───────────────────────────────────────────
  { d: '2025-11-03', t: 'moment', title: 'Kicking at the leaves', c: 'You discovered your legs.', m: ['clip-04'], loc: 'Tilden Park' },
  { d: '2025-11-07', t: 'story', title: 'What your hands do',
    c: "You hold one finger so tightly. When you're feeding, your other hand opens and closes slowly against Mom's collarbone, like you're keeping time to a song only you can hear. When you sleep, both arms go straight up over your head like you've just won something.",
    m: ['linen-06'] },
  { d: '2025-11-12', t: 'moment', m: ['window-07'] },
  { d: '2025-11-15', t: 'family', title: 'Aunt Priya visits',
    c: 'She flew in for three days and spent most of them making you do the face where your lips go into a perfect O.',
    m: ['window-08', 'morning-07'], who: ['Aunt Priya'] },
  { d: '2025-11-19', t: 'moment', title: 'Rain on the window', m: ['night-02'] },
  { d: '2025-11-27', t: 'first', title: 'First Thanksgiving', ms: 'First Thanksgiving',
    c: "Fourteen people, one very small guest of honor. You were passed around the table like the gravy.",
    m: ['bokeh-01', 'bokeh-02', 'autumn-07'], loc: "Grandma Ruth's", who: ['Grandma Ruth', 'Grandpa Lou', 'Aunt Priya'], tags: ['holiday', 'family'] },
  { d: '2025-11-29', t: 'moment', m: ['autumn-08'] },

  // ── December 2025 ───────────────────────────────────────────
  { d: '2025-12-04', t: 'moment', title: 'Tummy time negotiations', c: 'Thirty seconds. Then a formal complaint.', m: ['linen-07'] },
  { d: '2025-12-09', t: 'moment', title: 'Lights on the porch', m: ['holiday-01'] },
  { d: '2025-12-13', t: 'adventure', title: 'First snow', ms: 'First snow',
    c: "Up at the cabin. You stared at it falling for a long time and then sneezed.",
    m: ['winter-01', 'winter-02', 'winter-03', 'winter-04'], loc: 'Tahoe', who: ['Mom', 'Dad'], fav: true },
  { d: '2025-12-14', t: 'moment', title: 'Snow, quietly', m: ['clip-07'], loc: 'Tahoe' },
  { d: '2025-12-20', t: 'family', title: 'Grandpa Lou reads to you',
    c: 'The same book, four times, doing all the voices. You were asleep after one.',
    m: ['night-03'], who: ['Grandpa Lou'] },
  { d: '2025-12-25', t: 'first', title: 'First Christmas', ms: 'First Christmas',
    c: 'You loved the paper more than anything inside it. Honestly, fair.',
    m: ['holiday-02', 'holiday-03', 'holiday-05'], loc: 'Home', who: ['Mom', 'Dad', 'Grandma Ruth', 'Grandpa Lou'], fav: true, tags: ['holiday', 'christmas'] },
  { d: '2025-12-25', t: 'moment', title: 'Christmas morning', c: 'Ribbon everywhere.', m: ['clip-06'] },
  { d: '2025-12-31', t: 'story', title: 'A letter on New Year\'s Eve',
    c: "Dear Juno — this year you were born, and everything we thought was important got quietly rearranged. We stayed up until 9:40, which is midnight somewhere. Next year you'll eat food, and move on your own, and probably say something. We can't wait. We also wish you'd stay exactly this size forever. Both things are true. — Mom & Dad",
    m: ['holiday-04'], who: ['Mom', 'Dad'], fav: true },

  // ── January 2026 ────────────────────────────────────────────
  { d: '2026-01-04', t: 'milestone', title: 'First laugh', ms: 'First laugh',
    c: "Dad sneezed. You laughed — a real one, from the belly. He's been fake-sneezing ever since. We couldn't stop replaying this.",
    m: ['clip-05'], who: ['Dad'], fav: true },
  { d: '2026-01-09', t: 'moment', m: ['winter-05'] },
  { d: '2026-01-14', t: 'moment', title: 'Four months', c: 'Four months old. Somehow both forever and no time at all.', m: ['morning-08'] },
  { d: '2026-01-21', t: 'funny', title: 'The raspberry phase', c: 'You blew raspberries at everyone, including the cat next door.', m: ['linen-08', 'linen-09'] },
  { d: '2026-01-28', t: 'moment', title: 'Frost on the garden', m: ['winter-06', 'winter-07'] },

  // ── February 2026 ───────────────────────────────────────────
  { d: '2026-02-08', t: 'milestone', title: 'Rolled over', ms: 'Rolled over',
    c: 'Tummy to back, mid-sentence. You looked as surprised as we were.', m: ['clip-08'], loc: 'Living room' },
  { d: '2026-02-14', t: 'family', title: 'Valentines', c: 'Three valentines, one of them yours.', m: ['morning-09'], who: ['Mom', 'Dad'] },
  { d: '2026-02-20', t: 'story', title: 'Your sounds',
    c: "You've started talking. Not words — a long, serious stream of 'ah-goo' and 'bah' with real intonation, like you're explaining something complicated and we just aren't getting it. You pause for us to answer. When we do, you nod, which can't be right, but it's definitely a nod.",
    m: ['window-09'] },
  { d: '2026-02-25', t: 'moment', m: ['winter-08'] },

  // ── March 2026 ──────────────────────────────────────────────
  { d: '2026-03-16', t: 'milestone', title: 'First solid food', ms: 'First solid food',
    c: 'Sweet potato. Your face went through every emotion a person can have, then you opened your mouth for more.',
    m: ['morning-10', 'linen-10'], who: ['Mom', 'Dad'], fav: true, tags: ['food'] },
  { d: '2026-03-21', t: 'moment', title: 'First day of spring', m: ['garden-01', 'garden-02'], loc: 'Back garden' },
  { d: '2026-03-26', t: 'funny', title: 'Avocado: no', c: 'Pea: no. Banana: absolutely yes. Banana in the ear: also yes.', m: ['window-10'], tags: ['food'] },

  // ── April 2026 ──────────────────────────────────────────────
  { d: '2026-04-06', t: 'milestone', title: 'Sitting up on your own', ms: 'Sat up',
    c: 'Wobbly, proud, and very interested in what everyone else was doing up there.', m: ['garden-03'], loc: 'Back garden' },
  { d: '2026-04-12', t: 'family', title: 'Easter at Grandma Ruth\'s',
    c: 'You found exactly zero eggs and one very old tennis ball, which you would not let go of.',
    m: ['garden-04', 'garden-05', 'garden-06'], loc: "Grandma Ruth's", who: ['Grandma Ruth', 'Grandpa Lou'], tags: ['holiday'] },
  { d: '2026-04-20', t: 'first', title: 'First tooth', ms: 'First tooth',
    c: 'Bottom left. We found it because you bit Dad.', m: ['morning-01'], who: ['Dad'] },
  { d: '2026-04-27', t: 'story', title: 'The night you didn\'t sleep',
    c: "The tooth, mostly. We took turns walking the hallway — twenty-two steps each way, we counted. Around four, Sam put on the record Grandpa Lou gave us, very quietly, and you finally went still on his shoulder halfway through the second side. I stood in the doorway and watched you both sway for a long time. — Mom",
    m: ['night-04'], who: ['Mom', 'Dad'] },

  // ── May 2026 ────────────────────────────────────────────────
  { d: '2026-05-04', t: 'moment', title: 'The swing', c: 'Your first time on the baby swing. Pure, silent delight.', m: ['clip-09'], loc: 'Tilden Park' },
  { d: '2026-05-10', t: 'family', title: "Mom's first Mother's Day", c: 'Breakfast in bed, mostly eaten by you.', m: ['morning-07', 'garden-07'], who: ['Mom'], fav: true },
  { d: '2026-05-18', t: 'milestone', title: 'Crawling', ms: 'First crawl',
    c: "Backwards at first — you kept ending up under the couch, confused. Then one morning, forward, straight across the living room for Biscuit's tail.",
    m: ['clip-10'], loc: 'Living room', tags: ['biscuit'], fav: true },
  { d: '2026-05-24', t: 'moment', m: ['garden-08', 'garden-09'] },
  { d: '2026-05-30', t: 'adventure', title: 'Picnic in the hills', c: 'You ate grass. We let it go.', m: ['field-01', 'field-02'], loc: 'Tilden Park', who: ['Mom', 'Dad'] },

  // ── June 2026 ───────────────────────────────────────────────
  { d: '2026-06-06', t: 'adventure', title: 'First flight', ms: 'First trip',
    c: 'Oakland to San Diego to see Nana Rosa. You charmed row 14 and slept the entire descent.',
    m: ['field-03'], loc: 'San Diego', who: ['Nana Rosa'], tags: ['travel'] },
  { d: '2026-06-08', t: 'family', title: 'Nana Rosa\'s garden', c: 'She showed you every single tomato plant by name.', m: ['garden-10'], loc: 'San Diego', who: ['Nana Rosa'] },
  { d: '2026-06-15', t: 'moment', title: "Dad's first Father's Day", c: 'Matching hats. Yours stayed on for nine seconds.', m: ['field-04'], who: ['Dad'] },
  { d: '2026-06-21', t: 'milestone', title: 'Pulling up to stand', ms: 'Pulled up to stand',
    c: 'Using the coffee table, then the couch, then Biscuit, who was very patient about it.',
    m: ['window-02', 'window-05'], tags: ['biscuit'] },
  { d: '2026-06-28', t: 'funny', title: 'Waving at everyone', c: 'Strangers, the mailman, a parked car. Everyone gets a wave.', m: ['field-05'] },

  // ── July 2026 ───────────────────────────────────────────────
  { d: '2026-07-04', t: 'first', title: 'First time at the beach', ms: 'First time at the beach',
    c: "You hated the sand on your hands, loved the sand in your mouth, and screamed with joy every time a wave came in.",
    m: ['beach-01', 'beach-02', 'beach-03', 'beach-04'], loc: 'Stinson Beach', who: ['Mom', 'Dad'], fav: true },
  { d: '2026-07-04', t: 'adventure', title: 'Toes in the water', m: ['clip-11'], loc: 'Stinson Beach' },
  { d: '2026-07-12', t: 'story', title: 'What we want you to know about summer',
    c: "That it smells like sunscreen and cut grass. That the light lasts until after you're asleep. That Dad will always buy the peaches even though we have peaches. That the ocean is cold here, always, and everyone goes in anyway.",
    m: ['beach-05'], loc: 'Stinson Beach' },
  { d: '2026-07-19', t: 'moment', title: 'Lake cabin', m: ['beach-06', 'beach-07'], loc: 'Clear Lake', who: ['Grandma Ruth', 'Grandpa Lou'] },
  { d: '2026-07-26', t: 'moment', m: ['beach-08'] },

  // ── August 2026 ─────────────────────────────────────────────
  { d: '2026-08-02', t: 'milestone', title: 'First word', ms: 'First word',
    c: "'Dah.' We think it meant dog. Biscuit definitely thinks it meant dog. Dad maintains it meant Dad.",
    m: ['field-06'], tags: ['biscuit', 'words'], fav: true },
  { d: '2026-08-09', t: 'moment', title: 'Golden hour in the backyard', m: ['clip-12'], loc: 'Back garden' },
  { d: '2026-08-16', t: 'funny', title: 'The great spaghetti incident', c: 'We found spaghetti in your hair two days later.', m: ['bokeh-03'], tags: ['food'] },
  { d: '2026-08-22', t: 'story', title: 'Eleven months',
    c: "You have opinions now. About socks (against), about the dog (deeply for), about being put down when you'd rather be carried (strongly against). You laugh at your own jokes. You hand us things and take them back. You're becoming a person so fast we keep catching our breath.",
    m: ['window-08'] },
  { d: '2026-08-29', t: 'milestone', title: 'First steps', ms: 'First steps',
    c: "Three steps from the couch to Mom. Then you sat down hard and clapped for yourself, and so did we.",
    m: ['clip-13'], loc: 'Living room', who: ['Mom', 'Dad'], fav: true },

  // ── September 2026 ──────────────────────────────────────────
  { d: '2026-09-06', t: 'first', title: 'First haircut', ms: 'First haircut',
    c: 'One curl, kept in an envelope in this book\'s real-life drawer.', m: ['window-09', 'linen-06'] },
  { d: '2026-09-14', t: 'milestone', title: 'One whole year', ms: 'First birthday',
    c: "Cake on your face, your hands, your feet, and somehow Biscuit. Everyone you love in one backyard. Happy birthday, Juno.",
    m: ['bokeh-04', 'bokeh-05', 'bokeh-06', 'field-02'], loc: 'Back garden',
    who: ['Mom', 'Dad', 'Grandma Ruth', 'Grandpa Lou', 'Nana Rosa', 'Aunt Priya'], fav: true, tags: ['birthday'] },
  { d: '2026-09-15', t: 'story', title: 'A letter on your first birthday',
    c: "A year ago tonight we brought you home and didn't sleep. Tonight you're asleep in your own room with one sock on, and we're sitting on the couch looking through this book. There's so much we already can't remember, which is why we started writing it down. We hope one day you read this and know: you were so loved, every ordinary day of it. — Mom & Dad",
    m: ['night-05'], who: ['Mom', 'Dad'], fav: true },
  { d: '2026-09-21', t: 'moment', title: 'Autumn again', c: 'A year later, the same leaves.', m: ['autumn-09'] },
  { d: '2026-09-27', t: 'funny', title: "Stealing Dad's glasses", c: 'Your new favorite game. Dad has not seen clearly in a week.', m: ['morning-03'], who: ['Dad'] },
  { d: '2026-10-02', t: 'moment', title: 'Just a Thursday', m: ['night-06', 'linen-05'] },
];

export interface SeedData {
  baby: Baby;
  media: MediaItem[];
  memories: Memory[];
  milestones: Milestone[];
}

export function buildDemoSeed(): SeedData {
  const baby: Baby = {
    id: DEMO_BABY_ID,
    name: 'Juno Hale',
    birthDate: '2025-09-14',
    birthPlace: "St. Vincent's, Berkeley",
    birthTime: '4:12 am',
    birthWeight: '7 lb 2 oz',
    photoMediaId: 'm-morning-04',
    people: ['Mom', 'Dad', 'Grandma Ruth', 'Grandpa Lou', 'Nana Rosa', 'Aunt Priya', 'Biscuit'],
    createdAt: CREATED,
  };

  const mediaMap = new Map<string, MediaItem>();
  const memories: Memory[] = [];
  const milestones: Milestone[] = [];

  rows.forEach((r, i) => {
    const id = `mem-${String(i + 1).padStart(3, '0')}`;
    const mediaIds = (r.m ?? []).map((k) => {
      const item = mediaFor(k);
      mediaMap.set(item.id, item);
      return item.id;
    });
    const memory: Memory = {
      id, babyId: baby.id, type: r.t, title: r.title, caption: r.c, date: r.d, mediaIds,
      location: r.loc, people: r.who ?? [], tags: r.tags ?? [], favorite: !!r.fav,
      createdAt: `${r.d}T18:00:00.000Z`, updatedAt: `${r.d}T18:00:00.000Z`,
    };
    if (r.ms) {
      const msId = `ms-${id}`;
      memory.milestoneId = msId;
      milestones.push({
        id: msId, babyId: baby.id, title: r.ms, description: r.c, date: r.d, memoryIds: [id],
        photoMediaId: mediaIds.find((m) => mediaMap.get(m)?.kind === 'photo') ?? mediaIds[0],
      });
    }
    memories.push(memory);
  });

  return { baby, media: [...mediaMap.values()], memories, milestones };
}
